pwr<-read.csv("household_power_consumption.txt", sep = ";")
date1 <- as.Date(pwr$Date, "%d/%m/%Y")
DATE1 <- as.Date("01/02/2007", "%d/%m/%Y")
DATE2 <- as.Date("02/02/2007", "%d/%m/%Y")
spwr <- subset(pwr, date1>=DATE1 & date1<=DATE2)
spwr[,3]<-as.numeric(as.character(spwr[,3]))
spwr[,4]<-as.numeric(as.character(spwr[,4]))
spwr[,5]<-as.numeric(as.character(spwr[,5]))
spwr[,7]<-as.numeric(as.character(spwr[,7]))
spwr[,8]<-as.numeric(as.character(spwr[,8]))
spwr[,9]<-as.numeric(as.character(spwr[,9]))
z = c(1,1441,2880)
zl = c("Thu","Fri","Sat")
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
with(spwr, plot(Global_active_power,type="l",ylab="Global Active Power",xlab="",xaxt="n"))
axis(1, at=z,labels=zl)
with(spwr, plot(Voltage,type="l",ylab="Voltage",xlab="datetime",xaxt="n"))
axis(1, at=z,labels=zl)
with(spwr, plot(Sub_metering_1,type="l",ylab="Energy sub metering",col="black",xlab="",xaxt="n"))
with(spwr,points(Sub_metering_2,type="l",col="red"))
with(spwr,points(Sub_metering_3,type="l",col="blue"))
axis(1, at=z,labels=zl)
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub-metering 1", "Sub-metering 2", "Sub-metering 3"))
with(spwr, plot(Global_reactive_power,type="l",ylab="Global Reactive Power",xlab="datetime",xaxt="n"))
axis(1, at=z,labels=zl)


dev.off()