pwr<-read.csv("household_power_consumption.txt", sep = ";")
date1 <- as.Date(pwr$Date, "%d/%m/%Y")
DATE1 <- as.Date("01/02/2007", "%d/%m/%Y")
DATE2 <- as.Date("02/02/2007", "%d/%m/%Y")
spwr <- subset(pwr, date1>=DATE1 & date1<=DATE2)
spwr[,3]<-as.numeric(as.character(spwr[,3]))
png(filename = "plot1.png", width = 480, height = 480)
hist(spwr$Global_active_power, col = "red", main = "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.off()